Repository urfave/cli, pull requests merged in 2022-10, with the labels that each got.

#1511 Turn off docs publishing from v3 series
  .github/workflows/cli.yml
Labels: kind/documentation, area/v3

#1494 Bump declared module and internal usage to `/v3/`
  .github/workflows/cli.yml
  README.md
  altsrc/flag.go
  altsrc/flag_generated.go
  altsrc/flag_test.go
  altsrc/input_source_context.go
  altsrc/json_command_test.go
  altsrc/json_source_context.go
  altsrc/map_input_source.go
  altsrc/toml_command_test.go
  altsrc/toml_file_loader.go
  altsrc/yaml_command_test.go
  altsrc/yaml_file_loader.go
  altsrc/yaml_file_loader_test.go
  docs/v3/index.md
  go.mod
  go.sum
  godoc-current.txt
  internal/build/build.go
  internal/example-cli/example-cli.go
  internal/genflags/cmd/genflags/main.go
  internal/genflags/package_test.go
  internal/genflags/spec_test.go
  zz_generated.flags_test.go
Labels: kind/cleanup, area/v3

#1504 Ensure "generate" step runs in CI prior to diff check
  .github/workflows/cli.yml
  godoc-current.txt
  testdata/godoc-v2.x.txt
Labels: kind/bug, area/v2

#1442 Configure GenericFlag's Destination type as struct not pointer
  flag_generic.go
  flag_test.go
  godoc-current.txt
  testdata/godoc-v2.x.txt
Labels: area/v2, status/conflicts, status/waiting-for-response

#1430 fix: stop automatic sorting for --help
  app.go
  app_test.go
  category.go
  command.go
  command_test.go
  docs/v2/examples/flags.md
  godoc-current.txt
  help.go
  help_test.go
  template.go
  testdata/godoc-v2.x.txt
Labels: area/v2

#1526 Build and run `urfave-cli-genflags` via its `Makefile`
  cli.go
  cmd/urfave-cli-genflags/Makefile
  cmd/urfave-cli-genflags/main.go
Labels: kind/bug, kind/cleanup

#1498 Cleanup redundant code in App/Command
  altsrc/json_command_test.go
  altsrc/toml_command_test.go
  altsrc/yaml_command_test.go
  app.go
  app_test.go
  command.go
  command_test.go
  godoc-current.txt
  help.go
  help_test.go
  suggestions_test.go
  template.go
  testdata/godoc-v2.x.txt
Labels: kind/discussion, area/v2, kind/cleanup

#1525 Porting changes from `main` to `v3-dev-main` (circa 2022-10-09)
  .github/workflows/cli.yml
  Makefile
  app_test.go
  cli.go
  cmd/urfave-cli-genflags/Makefile
  cmd/urfave-cli-genflags/generated.gotmpl
  cmd/urfave-cli-genflags/generated_test.gotmpl
  cmd/urfave-cli-genflags/main.go
  command.go
  command_test.go
  flag.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_string_slice.go
  flag_test.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  flag_uint64_slice.go
  flag_uint_slice.go
  godoc-current.txt
  help.go
  help_test.go
  parse.go
  template.go
  zz_generated.flags.go
  zz_generated.flags_test.go
Labels: kind/maintenance
