Repository urfave/cli, pull requests merged in 2022-08, with the labels that each got.

#1438 Target minimum go 1.18 in v3-dev-main
  .github/workflows/cli.yml
  sliceflag.go
  sliceflag_pre18.go
  sliceflag_test.go
Labels: kind/cleanup

#1452 Shift supported go versions
  .github/workflows/cli.yml
  .gitignore
  cli.go
  godoc-current.txt
  testdata/godoc-v2.x.txt
Labels: kind/maintenance

#1448 Add support for alias in YAMLs
  altsrc/flag.go
  altsrc/flag_test.go
Labels: kind/feature
