Repository urfave/cli, pull requests merged in 2022-09, with the labels that each got.

#1480 Update version of codecov action
  .github/workflows/cli.yml
Labels: kind/maintenance

#1479 Add a few notes to release docs
  docs/RELEASING.md
Labels: kind/documentation

#1257 Add count option for bool flags
  cmd/urfave-cli-genflags/generated.gotmpl
  cmd/urfave-cli-genflags/main.go
  context.go
  docs/v2/examples/flags.md
  flag-spec.yaml
  flag.go
  flag_bool.go
  flag_test.go
  godoc-current.txt
  zz_generated.flags.go
Labels: kind/feature, area/v2

#1378 Feature:(Issue 1334) Add support for uint64slices
  .github/.codecov.yml
  altsrc/flag_test.go
  flag-spec.yaml
  flag_test.go
  flag_uint64_slice.go
  flag_uint_slice.go
  godoc-current.txt
  zz_generated.flags.go
  zz_generated.flags_test.go
Labels: kind/feature, area/v2

#1490 Move more functionality into internal/build/build.go
  .github/workflows/cli.yml
  Makefile
  docs/CONTRIBUTING.md
  flag-spec.yaml
  internal/build/build.go
  testdata/godoc-v2.x.txt
Labels: kind/maintenance, kind/cleanup

#1493 Accept the `MKDOCS_REMOTE_GITHUB_TOKEN` var as intended
  internal/build/build.go
Labels: kind/bug, kind/maintenance

#1337 Flag-level Action
  app.go
  app_test.go
  cmd/urfave-cli-genflags/go.sum
  command.go
  flag-spec.yaml
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  godoc-current.txt
  testdata/godoc-v2.x.txt
  zz_generated.flags.go
Labels: kind/feature, area/v2, status/conflicts

#1499 Fix help results inconsistency
  app_test.go
  command.go
  godoc-current.txt
  help.go
  help_test.go
  template.go
  testdata/godoc-v2.x.txt
Labels: kind/bug, area/v2

#1503 Remove nonexistent phony targets
  Makefile
Labels: area/v2, kind/cleanup
