Repository urfave/cli, pull requests merged in 2022-06, with the labels that each got.

#1409 Add SliceFlag wrapper and fix bugs in existing implementations
  flag_float64_slice.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_string_slice.go
  flag_test.go
  sliceflag.go
  sliceflag_pre18.go
  sliceflag_test.go
Labels: kind/bug, kind/feature, area/v2

#1119 Add word-wrap support, with wrap length provided by the user
  help.go
  help_test.go
  template.go
Labels: kind/feature, area/v2

#1418 Remove temporary go mod workaround
  .github/workflows/cli.yml
Labels: area/v2, kind/cleanup

#1423 Fix list formatting in v2 manual
  docs/v2/manual.md
Labels: kind/documentation, area/v2, kind/cleanup

#1428 Ignore dirs that are ignored in v2
  .gitignore
Labels: kind/cleanup, area/v1
