Repository urfave/cli, pull requests merged in 2022-04, with the labels that each got.

#1355 Ci config trimming
  .github/workflows/cli.yml
  .gitignore
Labels: kind/cleanup, area/v1

#1356 Merging 1135 fix flag parsing
  app_test.go
  command.go
  command_test.go
Labels: kind/bug, area/v1

#1351 Bump matrix of supported Go versions
  .github/workflows/cli.yml
  .gitignore
  docs/v2/manual.md
Labels: area/v2, kind/cleanup

#1357 Attempting to soften the barrier to entry
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/v1-bug-report.md
  .github/ISSUE_TEMPLATE/v2-bug-report.md
  .github/ISSUE_TEMPLATE/v2-feature-request.md
  .github/pull_request_template.md
Labels: kind/cleanup

#1352 Add Stale bot configuration per docs
  .github/stale.yml
Labels: area/v2, kind/cleanup

#1353 Drop references/usage of GO111MODULE
  README.md
Labels: area/v2, kind/cleanup

#1358 Switch branch references from `master` to `main`
  .github/ISSUE_TEMPLATE/v1-bug-report.md
  .github/ISSUE_TEMPLATE/v2-bug-report.md
  .github/ISSUE_TEMPLATE/v2-feature-request.md
  .github/workflows/cli.yml
  README.md
  app.go
  docs/CONTRIBUTING.md
Labels: area/v2, kind/cleanup

#1359 Update dependencies and go.mod spec
  .github/workflows/cli.yml
  go.mod
  go.sum
Labels: area/v2, kind/cleanup

#1360 show only subcommand flags with bash completion (#1186)
  help.go
  help_test.go
Labels: kind/bug, area/v2

#1361 Remove reflect calls for doc generation (#1259)
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_test.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  internal/build/build.go
Labels: kind/bug, area/v2, kind/cleanup

#1362 Don't call open("") backport
  flag.go
Labels: kind/bug, area/v1

#1370 Unshadow `context` package
  altsrc/flag.go
  altsrc/json_source_context.go
  altsrc/toml_file_loader.go
  altsrc/yaml_file_loader.go
  app.go
  app_test.go
  command.go
  command_test.go
  context.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  funcs.go
  help.go
Labels: area/v2, kind/cleanup

#1260 Add test case for short option handling
  flag_test.go
Labels: kind/bug, area/v2

#1262 Allow -ve values for int, float & duration
  altsrc/flag.go
  altsrc/flag_test.go
Labels: kind/bug, area/v2

#1374 Remove some unused code
  flag.go
  flag_test.go
Labels: area/v2, kind/cleanup

#1376 Do not apply altsrc input values that are not set
  altsrc/flag.go
  altsrc/flag_test.go
  altsrc/helpers_test.go
  altsrc/input_source_context.go
  altsrc/json_source_context.go
  altsrc/map_input_source.go
  altsrc/yaml_file_loader_test.go
  testdata/empty.yml
Labels: kind/bug, kind/feature, area/v2

#1346 Exclude hidden sub-command flags from docs
  docs.go
  docs_test.go
  fish.go
Labels: kind/bug, area/v2

#1375 Add `urfave_cli_no_docs` build tag
  .github/workflows/cli.yml
  README.md
  docs.go
  docs_test.go
  fish_test.go
  internal/build/build.go
Labels: kind/feature, area/v2

#1371 Cleaning up some release-related metadata & docs
  LICENSE
  README.md
  docs/CHANGELOG.md
  docs/RELEASING.md
Labels: area/v2, kind/cleanup

#1241 Accept multi-value input on slice flags
  app_test.go
  flag.go
  flag_float64_slice.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_string_slice.go
  flag_test.go
Labels: kind/bug, area/v2

#1379 [v1] fix CI, add Go 1.17.x and 1.18.x
  .github/workflows/cli.yml
  app_test.go
Labels: area/v1
