Repository urfave/cli, pull requests merged in 2022-05, with the labels that each got.

#1367 Simplified flag value access
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_test.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
Labels: kind/feature, area/v2

#1382 Generate flag types (again?)
  .github/workflows/cli.yml
  Makefile
  cli.go
  docs/CONTRIBUTING.md
  flag-spec.yaml
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  go.mod
  go.sum
  internal/build/build.go
  internal/genflags/cmd/genflags/main.go
  internal/genflags/generated.gotmpl
  internal/genflags/generated_test.gotmpl
  internal/genflags/package.go
  internal/genflags/package_test.go
  internal/genflags/spec.go
  internal/genflags/spec_test.go
  zz_generated.flags.go
  zz_generated.flags_test.go
Labels: kind/discussion, area/v2, kind/cleanup

#1385 Introduce a v2.x semver approval gate
  Makefile
  docs/CONTRIBUTING.md
  godoc-current.txt
  internal/build/build.go
  testdata/godoc-v2.x.txt
Labels: area/v2, kind/maintenance

#1393 Generate RequiredFlag and VisibleFlag implementations
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  internal/genflags/generated.gotmpl
  internal/genflags/generated_test.gotmpl
  internal/genflags/spec.go
  zz_generated.flags.go
  zz_generated.flags_test.go
Labels: area/v2, kind/cleanup

#1392 Mkdocs setup
  .github/workflows/cli.yml
  .gitignore
  Makefile
  docs/CNAME
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/index.md
  docs/migrate-v1-to-v2.md
  docs/v1/index.md
  docs/v1/manual.md
  docs/v2/index.md
  docs/v2/manual.md
  mkdocs-requirements.txt
  mkdocs.yml
Labels: kind/documentation, area/v2, kind/cleanup

#1390 Add suggestions support (#977)
  .github/workflows/cli.yml
  README.md
  app.go
  command.go
  docs/v2/manual.md
  go.mod
  go.sum
  godoc-current.txt
  help.go
  parse.go
  suggestions.go
  suggestions_test.go
  testdata/godoc-v2.x.txt
Labels: kind/feature, area/v2

#977 Add suggestions support
  app.go
  command.go
  docs/v2/manual.md
  go.mod
  go.sum
  help.go
  parse.go
  suggestions.go
  suggestions_test.go
Labels: kind/feature, area/v2, status/superseded

#1400 Docs publishing fixes
  .github/workflows/cli.yml
  Makefile
  internal/build/build.go
  mkdocs-requirements.txt
Labels: kind/bug, kind/documentation, area/v2

#1350 Auto-detect zsh via `SHELL` (#1218)
  app_test.go
  autocomplete/zsh_autocomplete
  docs/v2/manual.md
  help.go
  help_test.go
Labels: kind/bug, kind/documentation, area/v2, kind/cleanup

#1354 Merging mostynb report source of parse errors
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_test.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
Labels: kind/feature, area/v2

#1168 Report the source of a value when we cannot parse it
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_test.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
Labels: kind/feature, area/v2, status/superseded

#1365 Add a security policy document
  CODE_OF_CONDUCT.md
  docs/SECURITY.md
Labels: kind/documentation, area/v2

#1368 Add flag category support (#796)
  app.go
  app_test.go
  category.go
  command.go
  flag.go
  flag_bool.go
  flag_duration.go
  flag_float64.go
  flag_float64_slice.go
  flag_generic.go
  flag_int.go
  flag_int64.go
  flag_int64_slice.go
  flag_int_slice.go
  flag_path.go
  flag_string.go
  flag_string_slice.go
  flag_timestamp.go
  flag_uint.go
  flag_uint64.go
  godoc-current.txt
  internal/genflags/generated.gotmpl
  template.go
  testdata/godoc-v2.x.txt
  zz_generated.flags.go
Labels: kind/feature, area/v2

#1396 Introduce override hooks for suggestions
  app.go
  godoc-current.txt
  help.go
  suggestions.go
  suggestions_test.go
  testdata/godoc-v2.x.txt
Labels: kind/feature, area/v2

#1399 Point to the docs tree and site from top-level README
  README.md
  docs/index.md
Labels: area/v2, kind/cleanup

#1403 Run docs tests against current work tree
  docs/v2/manual.md
  internal/build/build.go
Labels: kind/bug, kind/documentation, area/v2

#1407 Add some missing go.sum entries needed with 1.16.x
  go.sum
Labels: area/v2, kind/cleanup
