Repository urfave/cli, pull requests merged in 2023-05, with the labels that each got.

#1708 Fix `incorrectTypeForFlagError` for unknowns
  altsrc/map_input_source.go
  altsrc/map_input_source_test.go
Labels: kind/bug, area/v2

#1722 Feat: Added tabular markdown writer
  docs.go
  docs_test.go
  fish_test.go
  godoc-current.txt
  template.go
  testdata/expected-tabular-markdown-custom-app-path.md
  testdata/expected-tabular-markdown-full.md
  testdata/godoc-v3.x.txt
Labels: kind/feature, area/v3

#1728 Bug/fix issue 1703
  help.go
  help_test.go
Labels: kind/bug, area/v2

#1738 Fix func name referenced in doc comment
  app.go
  godoc-current.txt
  testdata/godoc-v2.x.txt
Labels: kind/documentation, area/v2, kind/cleanup

#1744 Add some clarity around available versions and level of support
  docs/index.md
Labels: kind/documentation, area/v3
