Repository urfave/cli, pull requests merged in 2023-06, with the labels that each got.

#1748 Update dependencies for v1
  go.mod
  go.sum
Labels: kind/maintenance, area/v1

#1749 Update dependencies for v2
  go.mod
  go.sum
Labels: area/v2, kind/maintenance

#1752 Some docs housekeeping and minor cleanups
  .flake8
  LICENSE
  README.md
  docs/index.md
  flag.go
  flag_test.go
  flag_value_source.go
Labels: kind/documentation, kind/cleanup, area/v3

#1762 Bash completion nits
  autocomplete/bash_autocomplete
  docs/v2/examples/bash-completions.md
Labels: kind/documentation, area/v2, kind/cleanup

#1760 Reworking value source API
  command_test.go
  flag_bool_with_inverse.go
  flag_bool_with_inverse_test.go
  flag_impl.go
  flag_test.go
  flag_value_source.go
  flag_value_source_test.go
  godoc-current.txt
  internal/build/build.go
  testdata/godoc-v3.x.txt
  value_source.go
  value_source_test.go
Labels: kind/feature, kind/cleanup, area/v3

#1768 Collapse `uint` and `uint64` flag types
  command_test.go
  context_test.go
  flag_test.go
  flag_uint.go
  flag_uint64.go
  flag_uint64_slice.go
  flag_uint_slice.go
  godoc-current.txt
  testdata/godoc-v3.x.txt
Labels: kind/cleanup, area/v3

#1773 Rename `float64` types from `Float64` to `Float`
  command_test.go
  context_test.go
  examples_test.go
  flag_float.go
  flag_float64.go
  flag_float64_slice.go
  flag_float_slice.go
  flag_slice_base.go
  flag_test.go
  godoc-current.txt
  testdata/godoc-v3.x.txt
Labels: kind/cleanup, area/v3

#1779 Remove markdown/man docs support
  .github/workflows/cli.yml
  docs.go
  docs/index.md
  docs_test.go
  go.mod
  go.sum
  godoc-current.txt
  internal/build/build.go
  template.go
  testdata/godoc-v3.x.txt
Labels: kind/cleanup, area/v3

#1785 Feature: Add support for validation functions
  command_test.go
  errors.go
  flag_impl.go
  flag_int_slice.go
  flag_string_map.go
  flag_string_slice.go
  flag_uint_slice.go
  flag_validation_test.go
  godoc-current.txt
  testdata/godoc-v3.x.txt
Labels: area/v3
