Repository urfave/cli, pull requests merged in 2023-03, with the labels that each got.

#1691 Shift tested Go versions
  .github/workflows/cli.yml
Labels: kind/maintenance, area/v3

#1692 Shift tested Go versions in v2-maint
  .github/workflows/cli.yml
Labels: area/v2, kind/maintenance

#1693 Shift tested Go versions in v1-maint
  .github/workflows/cli.yml
Labels: kind/maintenance, area/v1

#1710 Preserve separator spec on subcommands
  command.go
  command_test.go
Labels: kind/bug, area/v2

#1712 Update dependencies for `v1-maint`
  go.mod
  go.sum
Labels: kind/maintenance, area/v1
